module.exports = {
    TAG                 : "api::tag.tag",
    LEAD                : "api::lead.lead",
    TASK                : "api::task.task",
    NOTE                : "api::note.note",
    USER                : "plugin::users-permissions.user",
    ROLE                : "plugin::users-permissions.role",
    COMPANY             : "api::company.company",
    INSIDER             : "api::insider.insider",
    CUSTOMER            : "api::customer.customer",
    DOCUMENT            : "api::document.document",
    INVITATION          : "api::invitation.invitation",
    CONTACT_GROUP       : "api::contact-group.contact-group",
    CONTACT_SOURCE      : "api::contact-source.contact-source",
    CONTACT_INTERACTION : "api::contact-interaction.contact-interaction",
}